import Head from 'next/head'
import { IBM_Plex_Mono } from '@next/font/google'
import styled from 'styled-components'

const IBMPlexMono = IBM_Plex_Mono({ 
  subsets: ['latin'], 
  weight: ["100", "200", "300", "400", "500", "600", "700"]
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledMain className={IBMPlexMono.className}>
        <h1>Hello</h1>
      </StyledMain>
    </>
  )
}

const StyledMain = styled.main`

`;
